name: Test Azure VM Connection

on:
  push:
    branches:
      - main

jobs:
  test-vm:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Azure Login
      uses: azure/login@v2.2.0
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Test VM Command
      run: |
        echo "{
          \"commandToExecute\": \"echo Hello from VM!\"
        }" > protected-settings.json

        az vm extension set \
          --resource-group "${{ secrets.RESOURCE_GROUP }}" \
          --vm-name "${{ secrets.VM_NAME }}" \
          --name "CustomScript" \
          --force-update \
          --publisher "Microsoft.Azure.Extensions" \
          --settings '{}' \
          --protected-settings @protected-settings.json
